### ISSUE TITLE
Build Failure with apache-oodt 0.7

### ISSUE THREAD

**Issue by sidhantsetia** [chrismattmann/bigtranslate#1]
While building apache-oodt 0.7 there is a build failure in CAS Protocol HTTP Implementation. The build fails as it does not pass the test cases. Need to update apache-oodt to the latest version.

**Comment by chrismattmann** [comment]
OK gotcha, @sidhantsetia . What platform are you on? Can you submit a PR to upgrade to OODT 0.10?

**Comment by chrismattmann** [comment]
Closed with #2
