### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by sidhantsetia** [chrismattmann/bigtranslate#3]
@chrismattmann 
Hello Professor,
I'm trying to build bigtranslate but it is failing in extensions.
Please find below the attached logs

Building Extensions 0.1
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.apache.oodt:cas-metadata:jar:0.10-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.oodt:cas-filemgr:jar:0.10-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.apache.oodt:pcs-core:jar:0.10-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Data Management System ............................ SUCCESS [0.949s]
[INFO] Extensions ........................................ FAILURE [0.054s]
[INFO] Resource Manager (Apache OODT) .................... SKIPPED
[INFO] PCS Config (Apache OODT) .......................... SKIPPED
[INFO] File Manager (Apache OODT) ........................ SKIPPED
[INFO] Workflow Manager (Apache OODT) .................... SKIPPED
[INFO] PGE (Apache OODT) ................................. SKIPPED
[INFO] Crawler (Apache OODT) ............................. SKIPPED
[INFO] Solr Catalog (Apache Solr) ........................ SKIPPED
[INFO] PCS Ops Interface (Apache OODT) ................... SKIPPED
[INFO] PCS Services (Apache OODT) ........................ SKIPPED
[INFO] Filemanager Product Services (Apache OODT) ........ SKIPPED
[INFO] Distribution (RADiX Distro of OODT) ............... SKIPPED
[INFO] Solr Webapp (Apache Solr) ......................... SKIPPED
[INFO] Web Applications (Apache OODT) .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.227s
[INFO] Finished at: Fri Oct 16 18:31:52 PDT 2015
[INFO] Final Memory: 12M/239M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project xdata-employment-extensions: Could not resolve dependencies for project gov.nasa.jpl.xdata:xdata-employment-extensions:jar:0.1: The following artifacts could not be resolved: org.apache.oodt:cas-metadata:jar:0.10-SNAPSHOT, org.apache.oodt:cas-filemgr:jar:0.10-SNAPSHOT, org.apache.oodt:pcs-core:jar:0.10-SNAPSHOT: Failure to find org.apache.oodt:cas-metadata:jar:0.10-SNAPSHOT in http://download.java.net/maven/2 was cached in the local repository, resolution will not be reattempted until the update interval of maven2 has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :xdata-employment-extensions

**Comment by sidhantsetia** [comment]
I found the cause for this. The oodt being used is 0.10-SNAPSHOT. As 0.10 is already released it should be changed to 0.11-SNAPSHOT if we still need to use the SNAPSHOT version. 
Should I change it to 0.11-SNAPSHOT or to 0.10 ?

**Comment by chrismattmann** [comment]
no the cause is that it's looking for xdata-deployment-extensions, as the error message states.

**Comment by chrismattmann** [comment]
Oh yea please update to 0.11-snapshot

**Comment by sidhantsetia** [comment]
Updated to 0.11-SNAPSHOT with #5 . Build is successful now.
