### ISSUE TITLE
bigtranslate namespace

### ISSUE THREAD

**Issue by sidhantsetia** [chrismattmann/bigtranslate#6]
Hello Professor,
What all needs to be changed in this regard?
Should I change all the artifactid from xdata-\* to bigtransalte?

Also in tasks,xml for workflow should I change the class to org.apache.oodt.cas.pge.StdPGETaskInstance from the previous one?

@chrismattmann

**Comment by chrismattmann** [comment]
yes, change all xdata-\* to bigtranslate. Also yes change to StdPGETaskInstance which is available in OODT.

**Comment by chrismattmann** [comment]
@sidhantsetia

**Comment by chrismattmann** [comment]
ping @sidhantsetia

**Comment by sidhantsetia** [comment]
I've pushed the changes for the namespace change. 
This issue has been resolved.
@chrismattmann
